services:
  armv7-dev:
    build: ./docker
    container_name: armv7-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    command: /bin/bash 