# 注意: 此workflow已被 run-test.yml 替代
# 新的workflow直接执行 run.sh 脚本进行测试
# 如需使用此workflow，请手动触发或修改触发器

name: Build ARMv7 Binary

# 已禁用 - 使用 run-test.yml 替代
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   release:
#     types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 安装ARM交叉编译工具链
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        
    - name: 验证工具链安装
      run: |
        arm-linux-gnueabihf-gcc --version
        echo "ARM交叉编译工具链安装成功"
        
    - name: 编译ARMv7二进制文件
      run: |
        make clean
        make demo_armv7
        
    - name: 验证二进制文件
      run: |
        file demo_armv7
        echo "二进制文件架构信息:"
        readelf -h demo_armv7 | grep Machine
        
    - name: 创建发布目录
      run: |
        mkdir -p release
        cp demo_armv7 release/
        cp main.c release/
        cp Makefile release/
        cp README.md release/
        
    - name: 创建版本信息文件
      run: |
        echo "构建时间: $(date)" > release/build_info.txt
        echo "Git提交: ${{ github.sha }}" >> release/build_info.txt
        echo "分支: ${{ github.ref_name }}" >> release/build_info.txt
        echo "目标架构: ARMv7" >> release/build_info.txt
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: armv7-binary
        path: release/
        retention-days: 30
        
    - name: 创建发布 (仅限标签推送)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        body: |
          ## ARMv7 二进制文件发布
          
          ### 构建信息
          - 构建时间: $(date)
          - Git提交: ${{ github.sha }}
          - 目标架构: ARMv7
          
          ### 文件说明
          - `demo_armv7`: ARMv7架构的可执行文件
          - `main.c`: 源代码
          - `Makefile`: 编译脚本
          - `build_info.txt`: 构建信息
          
          ### 使用方法
          ```bash
          # 在ARMv7设备上运行
          chmod +x demo_armv7
          ./demo_armv7
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 